name: doxblox
version: 0.0.1
description: web client for doxblox
dependencies:
  polymer: any
  intl: any
  unittest: any
  route: any
  event_bus:
    git: https://github.com/marcojakob/dart-event-bus.git
  html5_dnd:
    git: https://github.com/marcojakob/dart-html5-dnd.git
  makery_ui_assets:
    git: https://github.com/marcojakob/dart-makery-ui-assets.git
  makery_ui_split_panel:
    git: https://github.com/marcojakob/dart-makery-ui-split-panel.git
  makery_ui_tree_view:
    git: https://github.com/marcojakob/dart-makery-ui-tree-view.git
  widget:
    git: https://github.com/dart-lang/widget.dart.git
transformers:
- polymer:
    entry_points: web/index.html
